version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing NPM dependencies
      - npm i
  build:
    commands:
      - echo Running Tests started on `date`
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: sampleapp